// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Ventas.Infraestructure.Data.Context;
using Ventas.Infraestructure.Data.Entities;

namespace Ventas.Infraestructure.Data.Context.Configurations
{
    public partial class AsesoreConfiguration : IEntityTypeConfiguration<Asesore>
    {
        public void Configure(EntityTypeBuilder<Asesore> entity)
        {
            entity.HasKey(e => e.IdAsesor)
                .HasName("PK__asesores__A801FCE97F60ED59");

            entity.ToTable("asesores");

            entity.Property(e => e.IdAsesor).HasColumnName("idAsesor");

            entity.Property(e => e.Apellido)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("apellido");

            entity.Property(e => e.CantVentas).HasColumnName("cantVentas");

            entity.Property(e => e.MetaPropuesta).HasColumnName("metaPropuesta");

            entity.Property(e => e.Nombres)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("nombres");

            entity.Property(e => e.NroDoc)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("nroDoc")
                .IsFixedLength();

            entity.Property(e => e.TipoDoc)
                .HasMaxLength(4)
                .IsUnicode(false)
                .HasColumnName("tipoDoc")
                .IsFixedLength();

            entity.Property(e => e.Usuario)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("usuario");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Asesore> entity);
    }
}
