// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Ventas.Infraestructure.Data.Context;
using Ventas.Infraestructure.Data.Entities;

namespace Ventas.Infraestructure.Data.Context.Configurations
{
    public partial class ProductoConfiguration : IEntityTypeConfiguration<Producto>
    {
        public void Configure(EntityTypeBuilder<Producto> entity)
        {
            entity.HasKey(e => e.IdProducto)
                .HasName("PK__producto__07F4A13207020F21");

            entity.ToTable("productos");

            entity.Property(e => e.IdProducto).HasColumnName("idProducto");

            entity.Property(e => e.NombreCom)
                .HasMaxLength(70)
                .IsUnicode(false)
                .HasColumnName("nombreCom");

            entity.Property(e => e.Puntos)
                .HasColumnType("decimal(7, 4)")
                .HasColumnName("puntos");

            entity.Property(e => e.Tipo)
                .HasMaxLength(7)
                .IsUnicode(false)
                .HasColumnName("tipo")
                .IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Producto> entity);
    }
}
