// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Ventas.Infraestructure.Data.Entities;

namespace Ventas.Infraestructure.Data.Context
{
    public partial class VentasDatabaseContext
    {
        private IVentasDatabaseContextProcedures _procedures;

        public virtual IVentasDatabaseContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new VentasDatabaseContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IVentasDatabaseContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<listarVentasResult>().HasNoKey().ToView(null);
        }
    }

    public partial class VentasDatabaseContextProcedures : IVentasDatabaseContextProcedures
    {
        private readonly VentasDatabaseContext _context;

        public VentasDatabaseContextProcedures(VentasDatabaseContext context)
        {
            _context = context;
        }

        public virtual async Task<List<listarVentasResult>> listarVentasAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<listarVentasResult>("EXEC @returnValue = [dbo].[listarVentas]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
