// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
using Ventas.Infraestructure.Data.Context.Configurations;
using Ventas.Infraestructure.Data.Entities;
#nullable disable

namespace Ventas.Infraestructure.Data.Context
{
    public partial class VentasDatabaseContext : DbContext
    {
        public VentasDatabaseContext()
        {
        }

        public VentasDatabaseContext(DbContextOptions<VentasDatabaseContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Entities.Asesore> Asesores { get; set; }
        public virtual DbSet<Entities.Cliente> Clientes { get; set; }
        public virtual DbSet<Entities.Producto> Productos { get; set; }
        public virtual DbSet<Entities.Venta> Ventas { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.AsesoreConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ClienteConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ProductoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.VentaConfiguration());

            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
