// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ventas.Infraestructure.Data.Entities
{
    public partial class Asesore
    {
        public Asesore()
        {
            Venta = new HashSet<Venta>();
        }

        public int IdAsesor { get; set; }
        public string Usuario { get; set; }
        public string Nombres { get; set; }
        public string Apellido { get; set; }
        public string TipoDoc { get; set; }
        public string NroDoc { get; set; }
        public int? CantVentas { get; set; }
        public int? MetaPropuesta { get; set; }

        public virtual ICollection<Venta> Venta { get; set; }
    }
}