// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ventas.Infraestructure.Data.Entities
{
    public partial class Cliente
    {
        public Cliente()
        {
            Venta = new HashSet<Venta>();
        }

        public int IdCliente { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string TipoDoc { get; set; }
        public string NroDoc { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }

        public virtual ICollection<Venta> Venta { get; set; }
    }
}