// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ventas.Infraestructure.Data.Entities
{
    public partial class listarVentasResult
    {
        public string cliente { get; set; }
        public string nombreCom { get; set; }
        public string asesor { get; set; }
        public decimal? montoDesembolsado { get; set; }
        public string periodo { get; set; }
        public int? puntosObtenidos { get; set; }
        public DateTime? fechaVenta { get; set; }
    }
}
