// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ventas.Infraestructure.Data.Entities
{
    public partial class Producto
    {
        public Producto()
        {
            Venta = new HashSet<Venta>();
        }

        public int IdProducto { get; set; }
        public string NombreCom { get; set; }
        public string Tipo { get; set; }
        public decimal? Puntos { get; set; }

        public virtual ICollection<Venta> Venta { get; set; }
    }
}