// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ventas.Infraestructure.Data.Entities
{
    public partial class Venta
    {
        public int IdVenta { get; set; }
        public int? IdCliente { get; set; }
        public int? IdAsesor { get; set; }
        public int? IdProducto { get; set; }
        public string Periodo { get; set; }
        public int? PuntosObtenidos { get; set; }
        public DateTime? FechaVenta { get; set; }
        public decimal? MontoDesembolsado { get; set; }
        public int? EstadoRegistro { get; set; }

        public virtual Asesore IdAsesorNavigation { get; set; }
        public virtual Cliente IdClienteNavigation { get; set; }
        public virtual Producto IdProductoNavigation { get; set; }
    }
}